allowBuilds:
  '@swc/core': false
  edgedriver: false
  esbuild: false
  geckodriver: false
  keytar: false
  pre-commit: true
  puppeteer: true
  sharp: false
  spawn-sync: false
overrides:
  react: ^18.3.1